name: Build Resume

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm install -g resume-cli
    - run: resume export resume.json
    